### ISSUE TITLE
Cannot be used as channel payloads

### ISSUE THREAD

**Issue by altayhunter** [barweiss/go-tuple#16]
The documentation states that "Tuples can be used as slice or array items, map keys or values, and as channel payloads." However, attempting to use one results in a syntax error:
```
tup := make(chan (int, float64))
```
```
syntax error: unexpected comma, expecting )
```
If tuples cannot be used as channel payloads please update the documentation to make a note of this, or if they can be used as channel payloads please include examples of how to do so.

**Comment by barweiss** [comment]
Hi Altay!
Thank you for opening this issue!

I think there has been a misunderstanding.
This package offers various tuple types, `T<n>` where `n` is the number of elements in the tuple. So in order to achieve what you wanted here, the correct statement would be:

```go
tup := make(chan tuple.T2[int, float64])
```

I will try to find a way to clarify this in the documentation, maybe by giving an example.

**Comment by altayhunter** [comment]
Thanks for updating the documentation so quickly!
